name: mp_chart
description: A Flutter chart package just like AndroidMPChart, apply easy to use chart for Flutter.
version: 1.9.0
homepage: https://github.com/SunPointed/MPFlutterChart

environment:
  sdk: '>=3.10.8 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  intl: ^0.20.2
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  path_drawing: ^1.0.1
#  image_gallery_saver: ^1.7.1
  optimized_gesture_detector:
    git:
      url: https://github.com/absar/OptimizedGestureDetector.git
      #ref: null-safety
      path: ./
  vector_math: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
